---
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: ansible-ee-t
spec:
  serviceAccountName: pipeline
  template:
    ref: ansible-ee-tt
  bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
  interceptors:
    - params:
        - name: secretRef
          value:
            secretKey: secretToken
            secretName: ansible-ee-trigger-secret
        - name: eventTypes
          value:
            - push
      ref:
        kind: ClusterInterceptor
        name: github
