---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ansible-builder-
  labels:
    tekton.dev/pipeline: ansible-builder
spec:
  params:
    - name: git-url
      value: 'https://github.com/jayissi/ansible-execution-environments.git' # ChangeMe
    - name: git-revision
      value: main
    - name: ANSIBLE_BUILDER_IMAGE
      value: >-
        registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8:latest
    - name: NAME
      value: pipeline-test # ChangeMe
    - name: TAG
      value: '1.0'
    - name: CONTEXT
      value: context/
    - name: DOCKERFILE
      value: Containerfile
    - name: BUILD_ARGS
      value:
    - name: PUSH_ARGS
      value:
    - name: TLSVERIFY
      value: 'false'
    - name: PUSH_REGISTRY
      value: johnny-aap-hub.apps.kmod.gcpopenshift.info
  pipelineRef:
    name: ansible-builder
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: ee-repo
      persistentVolumeClaim:
        claimName: ansible-builder-pvc
