kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ansible-builder-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
