apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: ansible-ee-t
spec:
  bindings:
    - kind: TriggerBinding
      ref: ansible-ee-tb
  interceptors:
    - params:
        - name: secretRef
          value:
            secretKey: secretToken
            secretName: ansible-ee-trigger-secret
        - name: eventTypes
          value:
            - push
      ref:
        kind: ClusterInterceptor
        name: github
    - params:
        - name: filter
          value: ''
        - name: overlays
          value:
            - expression: body.head_commit.id.truncate(7)
              key: short_sha
      ref:
        kind: ClusterInterceptor
        name: cel
  serviceAccountName: pipeline
  template:
    ref: ansible-ee-tt
